### ISSUE TITLE
Wrong chapter numbering

### ISSUE THREAD

**Issue by janogarcia** [brandonskerritt/HowToGetAnyJobYouWant#2]
Thanks for this awesome guide, @autumnskerritt  👏

Just wanted to report a minor issue I noticed. It seems the chapter numbering is wrong everywhere I checked. It goes from _"Chapter 4 - Interviews"_ to _"Chapter 6 - Interview Questions"_, that is, _"Interview Questions"_ should be _"Chapter 5"_.

- [DEV.to](https://dev.to/autumnskerritt/how-to-get-any-job-you-want-a-guide-to-employability-skills-1i3m)
- [GitHub](https://github.com/autumnskerritt/HowToGetAnyJobYouWant/blob/cebe76ca7e1fb9a37bae9d808b222b27f06177ae/example4.html)
- [Amazon](https://user-images.githubusercontent.com/60790/56421232-ce2fb300-62a1-11e9-8aa2-c14a4437dce4.png)

Unsure about the PDF version, but I guess it could be affected as well.

**Comment by bee-san** [comment]
Hey @janogarcia ! Thanks for this!!! I'll fix this soon :) PS: Do you want your name in the thank yous of the book? Can go into PDF, I'll tweet you or something when the physical version is updated :)

**Comment by janogarcia** [comment]
No problem, Autumn. 😊 It's such a trivial contribution that I'm not sure I deserve that mention.

**Comment by bee-san** [comment]
Your name's in the book as a github contributor, but it's only in the html on github so far. Give me a day / two to re-upload to dev.to and my website etc :)
